#!/bin/bash
#
# Copyright 2019 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

cfg_dir="/var/lib/univention-appcenter/apps/jitsimeet/config/"
mkdir -p "$cfg_dir"

cleanup () {
    rm -rf $cfg_dir/jicofo || true
    rm -rf $cfg_dir/jvb || true
    rm -rf $cfg_dir/prosody || true
    rm -rf $cfg_dir/transcripts || true
    rm -rf $cfg_dir/web || true
}

if [ "$1" = "settings" ]; then
    cleanup
    univention-app reinitialize jitsimeet
fi

if [ "$1" = "remove" ]; then
    cleanup
fi

cat << "EOF" > /var/lib/univention-appcenter/apps/jitsimeet/config/vhost.conf
ProxyPass / http://localhost:8888/ retry=0
ProxyPassReverse / http://localhost:8888/
ProxyPreserveHost On
RequestHeader set X-Forwarded-Proto "https"
RewriteEngine on
RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule ^/?(.*) "ws://127.0.0.1:8888/$1" [P,L]
EOF

exit 0